language: csharp
solution: helloworld.sln
mono:
  - latest
dotnet: 2.1.502
script:
 - dotnet restore
deploy:
  provider: heroku
  api_key:
    secure: KEY
  app: elloworld
  on:
    repo: ericclifford/hello-world
